using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using System.Xml;


namespace WindowsTray
{
    static class Settings
    {
        public static readonly string IP = "IP";
        public static readonly string Port = "Port";

        public static void createSettingsFile()
        {
            //http://forum.codecall.net/topic/58239-c-tutorial-reading-and-writing-xml-files/
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;

            XmlWriter writer = XmlWriter.Create("settings.xml", settings);
            writer.WriteStartDocument();
            writer.WriteComment("Settings file generated by Home Control Suite");
            writer.WriteStartElement("settings");
            writer.WriteElementString(IP, "127.0.0.1");
            writer.WriteElementString(Port, "9999");
            writer.WriteEndElement();
            writer.WriteEndDocument();

            writer.Flush();
            writer.Close();
        }

        public static string getSetting(string attribute)
        {
            //http://www.stackoverflow.com/questions/4948027/overwrite-a-xml-file-value
            if (File.Exists("settings.xml"))
            {
                XmlDocument doc = new XmlDocument();
                doc.Load("settings.xml");
                XmlNode attributeNode = doc.SelectSingleNode("/settings/" + attribute);

                if (attributeNode != null)
                {
                    return attributeNode.InnerText;
                }
                else
                {
                    throw new Exception("Node not found");
                }
            }
            else
            {
                throw new Exception("Settings file not found");
            }
        }

        public static void saveSetting(string attribute, string data)
        {
            if (File.Exists("settings.xml"))
            {
                XmlDocument doc = new XmlDocument();
                doc.Load("settings.xml");
                XmlNode attributeNode = doc.SelectSingleNode("/settings/" + attribute);

                if (attributeNode == null)
                {
                    XmlNode nodeSettings = doc.SelectSingleNode("settings");
                    XmlNode newNode = doc.CreateNode(XmlNodeType.Element, attribute, null);
                    newNode.InnerText = data;
                    nodeSettings.AppendChild(newNode);
                }
                else
                {
                    attributeNode.InnerText = data;
                }
                doc.Save("settings.xml");
            }
        }
    }
}
